homepage:
    path: /
    controller: App\Controller\DefaultController::home

contact:
    path: /contact
    controller: App\Controller\DefaultController::contact

overons:
    path: /overons
    controller: App\Controller\DefaultController::overons